### ISSUE TITLE
No news shown

### ISSUE THREAD

**Issue by mrcfld** [microsoft/companynewspcfcontrol#2]
I follow the complete guide to add the companynewspcfcontrol to the account form, but no news are shown.
Thanks for your help
Marco

![image](https://user-images.githubusercontent.com/16242197/100348584-6564fc80-2fe7-11eb-9f01-ca9496cff85d.png)

**Comment by JohnnyRossi** [comment]
Same here, exact same issues, No news.  Is there a way to troubleshoot w/o downloading the code and running in IDE?

**Comment by allendm-msft** [comment]
My apologies for the delayed response here. 
The issue here could be related to the move of news search apis from cognitive services to bing search V7. The docs needs to be updated on the same and I will work with the team to get that done

Steps
1. Go to azure portal
2. Create a new bing search v7 resource
3. Use the endpoint and key created for this control
The endpoint would look like https://api.bing.microsoft.com/
What you need to enter in the control config is https://api.bing.microsoft.com/v7.0/news/search

This should address the issue. Let me know if this works

**Comment by user0604** [comment]
Thank you for your response. I have made modifications to the settings following the steps you provided above and have successfully integrated the Company news PCF control into the Account form as expected. 
I'm glad to hear that the docs will be updated too. Thanks again.

**Comment by allendm-msft** [comment]
Thanks for confirming @user0604
